### ISSUE TITLE
Compatibility issue with OpenCart v1.5.6

### ISSUE THREAD

**Issue by Vivekvvr** [softmonkeyjapan/opencart-excel-export#8]
We found your below Excel Plugin for Opencart very useful, unfortunately we are getting below issue during export option, Actually we are using Opencart 1.5.6 & I can see your plugin supporting only till 1.5.5.x Is this related to version upgrade issue?

Source
https://github.com/SoftMonkeyJapan/opencart-excel-export
http://kartono-loic.com/app/webroot/excel-export/documentation/
​Issue:​

<b>Fatal error</b>:  Class 'ZipArchive' not found in <b>/home/sdadmin/public_html/aromax/system/PHPExcel/Classes/PHPExcel/Writer/Excel2007.php</b> on line <b>205</b><br />

**Comment by softmonkeyjapan** [comment]
Hi,
Thank you for your feedback. I didn't test the extension on 1.5.6 yet, but the problem you are mentionning is not related to the `opencart-excel-export` extension, neither to a version problem.  
The extension use the `PHPExcel` library to generate Excel files. This library require you to enable the `php_zip` extension within your `php.ini` file. This php extension is mandatory.  

Are you able to modify the `php.ini` on your hosting server?

**Comment by Vivekvvr** [comment]
Hi 
Thanks a lot for your quick response, we will let you know if we have any other issue in 1.5.6, May I know when you have planned for 1.5.6 release

**Comment by sureshsm** [comment]
Hi,
We found your Export Excel Plugin for Opencart ,After installation in my website,  unfortunately we didn't see the Export menu in my site back end admin panel, Actually we are using Opencart 1.5.6 & I can see your plugin supporting only till 1.5.5.x Is this related to version upgrade issue or any other issue? kindly tell me the solutions.

**Comment by softmonkeyjapan** [comment]
Hi,
I just checked and the plugin is working under 1.5.6.4 (the latest version at the time of this writing). So I updated the README file and the branch name as well. Regarding the export menu, did you install `vqmod`? https://code.google.com/p/vqmod/downloads/list
You need it in order to see the menu appears.

**Comment by sureshsm** [comment]
Hi,
Yeah, Now i installed your vqmod-2.4.1-opencart.zip file in my website, unfortunately it's showing some issue in back end admin panel. I think may be we are already created some custom vqmod files. How to rectify this Fatal error, kindly tell me.

issue : 
Fatal error: Cannot instantiate abstract class VQMod in /home/sdadmin/public_html/aromax/admin/index.php on line 20

**Comment by softmonkeyjapan** [comment]
Hi there,
I've tried to install the extension from 1.5.4 to 1.5.6 using vqmod and I cannot reproduce the error. 
I guess the vqmod installer bug at some point due to some permissions restrictions on your **index.php** maybe.
Please try to make a manual install : https://code.google.com/p/vqmod/wiki/Install_OpenCart
Let me know how it goes

**Comment by Vivekvvr** [comment]
Thank you very much for your inputs, the plugin is working great. Now we are customizing for our needs.

**Comment by softmonkeyjapan** [comment]
You're welcome. If you guys add some new functionalities that you think could be great to have, don't hesitate to make a pull request :+1:
